/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tttTDD.Java;

public class App {

    public static void main(String[] args) {
        ConsoleClient console = new ConsoleClient();
        console.startGame();
    }
}
